import type { GenericSubPillarConfig } from './genericTypes';
import { clarityBehaviorData, cartRecoveryData, trustSocialProofData, returnsFlowData, orderTrackingData, codCheckoutData, productOptionsData, subscriptionOpportunityData, wishlistData, storeLocatorData, mobileUxData, priorityIssues } from '../../data/cro/cro.mock';

const status = (score: number) => score >= 85 ? 'Excellent' : score >= 70 ? 'Good' : score >= 50 ? 'Needs Work' : 'Critical';
const issueSet = (key: string) => priorityIssues.filter((issue) => issue.areaKey === key).map((issue) => ({ id: issue.id, severity: issue.severity, title: issue.title, affected: issue.affectedPages, recommendation: issue.recommendation }));
const make = (key: string, title: string, description: string, score: number, analyzedLabel: string, analyzed: number, healthy: number, metrics: GenericSubPillarConfig['metrics'], breakdown: GenericSubPillarConfig['breakdown']): GenericSubPillarConfig => ({ pillar: 'cro', pillarLabel: 'CRO', key, title, description, score, statusLabel: status(score), analyzedLabel, analyzed, healthy, metrics, breakdown, issues: issueSet(key) });
const split = (good: number, warning: number, critical: number) => [{ label: 'Healthy', value: good, color: 'bg-success-500' }, { label: 'Needs work', value: warning, color: 'bg-warning-500' }, { label: 'Critical', value: critical, color: 'bg-critical-500' }];

export const croPillarCatalog: Record<string, GenericSubPillarConfig> = {
  'cro/clarity': make('clarity', 'Clarity / Behavior Readiness', 'Remove hesitation by making the next action obvious across the storefront.', clarityBehaviorData.score, 'Pages', clarityBehaviorData.pagesAnalyzed, clarityBehaviorData.clearCta, [{ label: 'Clear CTA pages', value: clarityBehaviorData.clearCta, description: 'pages make the next action obvious' }, { label: 'Weak CTA pages', value: clarityBehaviorData.weakCta, description: 'pages need clearer calls to action' }, { label: 'Missing CTA pages', value: clarityBehaviorData.missingCta, description: 'pages have no clear primary action' }], split(clarityBehaviorData.clearCta, clarityBehaviorData.weakCta, clarityBehaviorData.missingCta)),
  'cro/cart-recovery': make('cart-recovery', 'Cart Recovery', 'Recover high-intent shoppers with complete, timely, and measurable recovery flows.', cartRecoveryData.score, 'Abandoned carts', cartRecoveryData.abandonedCarts, cartRecoveryData.recoveredLast30Days, [{ label: 'Recovery opportunity', value: `$${cartRecoveryData.recoveryOpportunity.toLocaleString()}`, description: 'estimated revenue opportunity' }, { label: 'Active flows', value: cartRecoveryData.activeFlows, description: 'recovery flows currently active' }, { label: 'Missing flows', value: cartRecoveryData.missingFlows, description: 'recovery journeys not yet configured' }], split(cartRecoveryData.recoveredLast30Days, cartRecoveryData.activeFlows, cartRecoveryData.missingFlows)),
  'cro/trust': make('trust', 'Trust & Social Proof', 'Make confidence visible with reviews, trust signals, and evidence close to the buying decision.', trustSocialProofData.score, 'Products', trustSocialProofData.productsAnalyzed, trustSocialProofData.wellReviewed, [{ label: 'Well reviewed', value: trustSocialProofData.wellReviewed, description: 'products have meaningful review coverage' }, { label: 'No reviews', value: trustSocialProofData.noReviews, description: 'products need social proof' }, { label: 'Trust coverage', value: `${trustSocialProofData.trustBadgeCoverage}%`, description: 'coverage across trust signals' }], [{ label: 'Well reviewed', value: trustSocialProofData.wellReviewed, color: 'bg-success-500' }, { label: 'No reviews', value: trustSocialProofData.noReviews, color: 'bg-critical-500' }]),
  'cro/returns': make('returns', 'Returns Flow', 'Make returns easy to understand and complete without unnecessary support friction.', returnsFlowData.score, 'Orders', returnsFlowData.ordersAnalyzed, returnsFlowData.selfServiceReturns, [{ label: 'Self-service returns', value: returnsFlowData.selfServiceReturns, description: 'returns resolved without manual handling' }, { label: 'Manual returns', value: returnsFlowData.manualReturns, description: 'returns still require support' }, { label: 'Policy clarity', value: `${returnsFlowData.policyClarityScore}/100`, description: 'clarity of the current returns policy' }], [{ label: 'Self service', value: returnsFlowData.selfServiceReturns, color: 'bg-success-500' }, { label: 'Manual', value: returnsFlowData.manualReturns, color: 'bg-warning-500' }]),
  'cro/tracking': make('tracking', 'Order Tracking', 'Keep customers informed after checkout with reliable tracking and proactive updates.', orderTrackingData.score, 'Orders', orderTrackingData.ordersAnalyzed, orderTrackingData.ordersWithTracking, [{ label: 'With tracking', value: orderTrackingData.ordersWithTracking, description: 'orders include tracking information' }, { label: 'Without tracking', value: orderTrackingData.ordersWithoutTracking, description: 'orders need delivery visibility' }, { label: 'Branded page coverage', value: `${orderTrackingData.brandedTrackingPageCoverage}%`, description: 'orders use a branded tracking experience' }], [{ label: 'Tracked', value: orderTrackingData.ordersWithTracking, color: 'bg-success-500' }, { label: 'Missing', value: orderTrackingData.ordersWithoutTracking, color: 'bg-warning-500' }]),
  'cro/cod': make('cod', 'COD Checkout Quality', 'Reduce failed deliveries and fraud risk with a clearer, better-validated COD checkout.', codCheckoutData.score, 'COD orders', codCheckoutData.codEligibleOrders, codCheckoutData.codEligibleOrders - Math.round(codCheckoutData.codEligibleOrders * codCheckoutData.validationErrorRate / 100), [{ label: 'Validation error rate', value: `${codCheckoutData.validationErrorRate}%`, description: 'COD checkouts encounter validation errors' }, { label: 'Order share', value: `${codCheckoutData.codOrderShare}%`, description: 'orders use cash on delivery' }, { label: 'Refusal rate', value: `${codCheckoutData.codReturnRefusalRate}%`, description: 'COD orders are refused on delivery' }], [{ label: 'Valid checkout', value: 100 - codCheckoutData.validationErrorRate, color: 'bg-success-500' }, { label: 'Errors', value: codCheckoutData.validationErrorRate, color: 'bg-critical-500' }]),
  'cro/options': make('options', 'Product Options & Add-ons', 'Help shoppers choose confidently with complete variants, guides, and relevant add-ons.', productOptionsData.score, 'Products', productOptionsData.productsAnalyzed, productOptionsData.productsWithVariants, [{ label: 'With variants', value: productOptionsData.productsWithVariants, description: 'products expose useful options' }, { label: 'With add-ons', value: productOptionsData.productsWithAddOns, description: 'products support cross-sell opportunities' }, { label: 'Missing size guide', value: productOptionsData.missingSizeGuide, description: 'products need fit guidance' }], [{ label: 'Configured', value: productOptionsData.productsWithVariants, color: 'bg-success-500' }, { label: 'Missing guide', value: productOptionsData.missingSizeGuide, color: 'bg-warning-500' }]),
  'cro/subscription': make('subscription', 'Subscription Opportunity', 'Turn replenishment behavior into a clear, convenient recurring purchase option.', subscriptionOpportunityData.score, 'Subscribable products', subscriptionOpportunityData.subscribableProducts, subscriptionOpportunityData.productsWithSubscription, [{ label: 'With subscription', value: subscriptionOpportunityData.productsWithSubscription, description: 'eligible products offer recurring purchase' }, { label: 'Missing subscription', value: subscriptionOpportunityData.productsMissingSubscription, description: 'eligible products miss the option' }, { label: 'Adoption rate', value: `${subscriptionOpportunityData.subscriptionAdoptionRate}%`, description: 'share of eligible orders using subscription' }], [{ label: 'Enabled', value: subscriptionOpportunityData.productsWithSubscription, color: 'bg-success-500' }, { label: 'Missing', value: subscriptionOpportunityData.productsMissingSubscription, color: 'bg-warning-500' }]),
  'cro/wishlist': make('wishlist', 'Wishlist', 'Capture save-for-later intent and bring high-intent shoppers back to the catalog.', wishlistData.score, 'Theme pages', wishlistData.themePageCoverage, Math.round(wishlistData.themePageCoverage * wishlistData.wishlistToPurchaseRate / 100), [{ label: 'Wishlist users', value: wishlistData.activeWishlistUsers, description: 'shoppers currently saving products' }, { label: 'Never wishlisted', value: wishlistData.productsNeverWishlisted, description: 'products have no wishlist activity' }, { label: 'To-cart rate', value: `${wishlistData.wishlistToCartRate}%`, description: 'wishlisted items that reach cart' }], [{ label: 'Active intent', value: wishlistData.activeWishlistUsers, color: 'bg-success-500' }, { label: 'No activity', value: wishlistData.productsNeverWishlisted, color: 'bg-warning-500' }]),
  'cro/locator': make('locator', 'Store Locator', 'Make physical locations easy to find with complete, trustworthy location information.', storeLocatorData.score, 'Locations', storeLocatorData.totalLocations, storeLocatorData.completeLocations, [{ label: 'Complete locations', value: storeLocatorData.completeLocations, description: 'locations have complete details' }, { label: 'Missing map pins', value: storeLocatorData.missingMapPin, description: 'locations need accurate geocoding' }, { label: 'Missing hours', value: storeLocatorData.missingHours, description: 'locations need opening hours' }], [{ label: 'Complete', value: storeLocatorData.completeLocations, color: 'bg-success-500' }, { label: 'Needs data', value: storeLocatorData.totalLocations - storeLocatorData.completeLocations, color: 'bg-warning-500' }]),
  'cro/mobile-ux': make('mobile-ux', 'Mobile UX', 'Remove mobile friction from tap targets, layout, and mobile conversion paths.', mobileUxData.score, 'Pages', mobileUxData.pagesAnalyzed, mobileUxData.good, [{ label: 'Good pages', value: mobileUxData.good, description: 'pages meet mobile usability expectations' }, { label: 'Needs improvement', value: mobileUxData.needsImprovement, description: 'pages need mobile refinement' }, { label: 'Critical pages', value: mobileUxData.critical, description: 'pages block a healthy mobile journey' }], split(mobileUxData.good, mobileUxData.needsImprovement, mobileUxData.critical)),
};
